services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aRsdCc44nVzF5@%
      POSTGRES_DB: grocery
    volumes:
      - groceryData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - internal
  backend:
    build: ./backend
    depends_on:
      - database
    networks:
      - internal
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: aRsdCc44nVzF5@%
      DB_NAME: grocery
      DATABASE_URL: postgresql://postgres:aRsdCc44nVzF5@%@database:5432/grocery

  frontend:
    build: ./frontend
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - internal
    environment:
       - VITE_API_URL=/api
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - internal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  groceryData:


networks:
  internal:
    driver: bridge